import turtle
avery=turtle.Pen()
kate=turtle.Pen()
avery.forward(50)
#avery.right(90)
kate.left(90)
kate.forward(50)
jacob=turtle.Pen()
jacob.left(180)
jacob.forward(50)
kate=turtle.Pen()
kate.right(90)
kate.forward(50)
turtle.done()
